const books = [
  {
    id: 1,
    name: "Clean Code: A Handbook of Agile Software Craftsmanship",
    author: "Robert C. Martin",
    price: 34.99,
    isFavorite: false,
    rating: 5,
    publishYear: 2008,
    image: "https://example.com/clean-code.jpg",
  },
  {
    id: 2,
    name: "The Pragmatic Programmer: Your Journey to Mastery",
    author: "Andrew Hunt, David Thomas",
    price: 42.5,
    isFavorite: false,
    rating: 4,
    publishYear: 1999,
    image: "https://example.com/pragmatic-programmer.jpg",
  },
  {
    id: 3,
    name: "JavaScript: The Good Parts",
    author: "Douglas Crockford",
    price: 29.99,
    isFavorite: false,
    rating: 4,
    publishYear: 2008,
    image: "https://example.com/javascript-good-parts.jpg",
  },
  {
    id: 4,
    name: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    price: 39.95,
    isFavorite: false,
    rating: 4,
    publishYear: 1994,
    image: "https://example.com/design-patterns.jpg",
  },
  {
    id: 5,
    name: "Python Crash Course",
    author: "Eric Matthes",
    price: 25.8,
    isFavorite: false,
    rating: 5,
    publishYear: 2015,
    image: "https://example.com/python-crash-course.jpg",
  },
  {
    id: 6,
    name: "The Mythical Man-Month: Essays on Software Engineering",
    author: "Frederick P. Brooks Jr.",
    price: 33.25,
    isFavorite: false,
    rating: 4,
    publishYear: 1975,
    image: "https://example.com/mythical-man-month.jpg",
  },
  {
    id: 7,
    name: "Code Complete: A Practical Handbook of Software Construction",
    author: "Steve McConnell",
    price: 37.5,
    isFavorite: false,
    rating: 5,
    publishYear: 2004,
    image: "https://example.com/code-complete.jpg",
  },
  {
    id: 8,
    name: "Eloquent JavaScript: A Modern Introduction to Programming",
    author: "Marijn Haverbeke",
    price: 28.99,
    isFavorite: false,
    rating: 4,
    publishYear: 2011,
    image: "https://example.com/eloquent-javascript.jpg",
  },
];

export default books;
